prospects_dict = {
    "AI ML Specialist": {
        "job_description": "AI ML Specialists are professionals who leverage machine learning algorithms and artificial intelligence to analyze and interpret complex data...",
        "prerequisites": "A degree in computer science, data science, or a related field is typically required. Proficiency in programming languages such as Python is essential...",
        "job_stats": "Average CTC: $120,000 per year",
        "skill_enhancement": "To excel in this role, professionals can enhance their skills in machine learning, deep learning, natural language processing, and statistical analysis...",
        "courses_reference": 'Coursera - Machine Learning Specialization, edX - AI for Everyone, Books - "Hands-On Machine Learning with Scikit-Learn and TensorFlow"',
        "job_prospects": "AI ML Specialists are in high demand, with opportunities in industries such as technology, healthcare, finance, and more.",
    },
    "API Integration Specialist": {
        "job_description": "API Integration Specialists play a key role in designing, implementing, and maintaining application programming interfaces (APIs) to facilitate seamless communication between different software systems...",
        "prerequisites": "A bachelor's degree in computer science or a related field is preferred. Strong programming skills and a solid understanding of RESTful APIs are essential...",
        "job_stats": "Average CTC: $100,000 per year",
        "skill_enhancement": "To excel in this role, professionals can enhance their skills in API design, integration protocols, security, and versioning...",
        "courses_reference": 'Udemy - API Design and Integration, Pluralsight - Mastering API Security, Books - "RESTful API Design Patterns"',
        "job_prospects": "API Integration Specialists are crucial for organizations with diverse software systems, providing seamless communication between applications.",
    },
    "Application Support Engineer": {
        "job_description": "Application Support Engineers are responsible for providing technical support and troubleshooting assistance for software applications to ensure their smooth operation...",
        "prerequisites": "A degree in computer science, information technology, or a related field is typically required. Strong problem-solving and communication skills are essential...",
        "job_stats": "Average CTC: $80,000 per year",
        "skill_enhancement": "To excel in this role, professionals can enhance their skills in application troubleshooting, customer support, and scripting languages...",
        "courses_reference": 'LinkedIn Learning - IT Support/Help Desk, Udacity - Technical Support Fundamentals, Books - "The Practice of System and Network Administration"',
        "job_prospects": "Application Support Engineers are in demand across various industries, ensuring the smooth operation of software applications.",
    },
    "Business Analyst": {
        "job_description": "Business Analysts analyze and interpret business data to provide insights for decision-making. They work closely with stakeholders to understand business needs and formulate data-driven recommendations...",
        "prerequisites": "A degree in business, finance, or a related field is typically required. Strong analytical and communication skills are essential...",
        "job_stats": "Average CTC: $90,000 per year",
        "skill_enhancement": "To excel in this role, professionals can enhance their skills in data analysis, business intelligence tools, and communication...",
        "courses_reference": 'Coursera - Business Analytics Specialization, edX - Data Science and Machine Learning for Business Analysis, Books - "Business Analysis Techniques"',
        "job_prospects": "Business Analysts play a crucial role in helping organizations make informed decisions based on data.",
    },
    "Customer Service Executive": {
        "job_description": "Customer Service Executives are responsible for ensuring excellent customer satisfaction by addressing customer inquiries, resolving issues, and providing support...",
        "prerequisites": "A degree in business, communication, or a related field may be preferred. Strong communication and interpersonal skills are essential...",
        "job_stats": "Average CTC: $50,000 per year",
        "skill_enhancement": "To excel in this role, professionals can enhance their skills in customer relationship management, communication, and problem-solving...",
        "courses_reference": 'LinkedIn Learning - Customer Service Foundations, Udemy - Customer Success: How to Reduce Churn & Increase Customer Retention, Books - "Customer Service Skills for Success"',
        "job_prospects": "Customer Service Executives are vital for organizations aiming to provide excellent service and maintain positive customer relationships.",
    },
    "Cyber Security Specialist": {
        "job_description": "Cyber Security Specialists are tasked with protecting computer systems and networks from cyber threats, attacks, and unauthorized access...",
        "prerequisites": "A degree in computer science, information technology, or a related field is typically required. Strong knowledge of cybersecurity principles and technologies is essential...",
        "job_stats": "Average CTC: $110,000 per year",
        "skill_enhancement": "To excel in this role, professionals can enhance their skills in ethical hacking, network security, and security risk management...",
        "courses_reference": 'Cybrary - Ethical Hacking Course, Udacity - Cybersecurity for Business, Books - "Hacking: The Art of Exploitation"',
        "job_prospects": "Cyber Security Specialists are in high demand as organizations prioritize securing their digital assets against evolving cyber threats.",
    },
    "Data Scientist": {
        "job_description": "Data Scientists analyze and interpret complex data sets to inform business decision-making. They employ statistical methods, machine learning, and data visualization to extract meaningful insights...",
        "prerequisites": "A degree in data science, statistics, or a related field is typically required. Strong programming skills, especially in languages like Python and R, are essential...",
        "job_stats": "Average CTC: $130,000 per year",
        "skill_enhancement": "To excel in this role, professionals can enhance their skills in machine learning, data visualization, and statistical analysis...",
        "courses_reference": 'Coursera - Data Science Specialization, edX - Python for Data Science, Books - "The Art of Data Science"',
        "job_prospects": "Data Scientists are sought after in various industries for their ability to derive valuable insights from data.",
    },
    "Database Administrator": {
        "job_description": "Database Administrators manage and organize databases to ensure efficient data storage, retrieval, and security. They optimize database performance and troubleshoot issues...",
        "prerequisites": "A degree in computer science, information technology, or a related field is typically required. Strong knowledge of database management systems (DBMS) is essential...",
        "job_stats": "Average CTC: $100,000 per year",
        "skill_enhancement": "To excel in this role, professionals can enhance their skills in database design, SQL query optimization, and data security...",
        "courses_reference": 'Udemy - The Complete Oracle SQL Certification Course, LinkedIn Learning - SQL Essential Training, Books - "Database Management Systems"',
        "job_prospects": "Database Administrators play a crucial role in managing and securing an organization's valuable data.",
    },
    "Graphics Designer": {
        "job_description": "Graphics Designers create visual concepts and designs for various projects and products. They use their creativity and design skills to communicate messages effectively through visual elements...",
        "prerequisites": "A degree in graphic design, visual arts, or a related field is typically required. Proficiency in graphic design software such as Adobe Creative Suite is essential...",
        "job_stats": "Average CTC: $70,000 per year",
        "skill_enhancement": "To excel in this role, professionals can enhance their skills in graphic design principles, typography, and digital illustration...",
        "courses_reference": 'Skillshare - Graphic Design Basics: Core Principles for Visual Design, Udacity - Graphic Design Basics, Books - "The Non-Designer\'s Design Book"',
        "job_prospects": "Graphics Designers contribute to the visual identity of products, brands, and campaigns, making their role essential in various industries.",
    },
    "Hardware Engineer": {
        "job_description": "Hardware Engineers design, develop, and test computer hardware components. They work on the design and implementation of computer systems, circuit boards, and other hardware components...",
        "prerequisites": "A degree in electrical engineering, computer engineering, or a related field is typically required. Strong knowledge of hardware design principles and computer architecture is essential...",
        "job_stats": "Average CTC: $90,000 per year",
        "skill_enhancement": "To excel in this role, professionals can enhance their skills in hardware design, computer architecture, and testing methodologies...",
        "courses_reference": 'Coursera - Computer Architecture, edX - Digital Systems: From Logic Gates to Processors, Books - "Computer Organization and Design"',
        "job_prospects": "Hardware Engineers play a crucial role in the development and innovation of computer hardware technologies.",
    },
    "Helpdesk Engineer": {
        "job_description": "Helpdesk Engineers provide technical support and assistance to end-users within an organization. They address and resolve IT-related issues, ensuring smooth operations...",
        "prerequisites": "A degree in information technology, computer science, or a related field may be preferred. Strong communication and problem-solving skills are essential...",
        "job_stats": "Average CTC: $60,000 per year",
        "skill_enhancement": "To excel in this role, professionals can enhance their skills in IT support, troubleshooting, and customer service...",
        "courses_reference": 'Udemy - IT Support and Help Desk Training, LinkedIn Learning - CompTIA A+ (220-1001) Cert Prep, Books - "ITIL Foundation Essentials"',
        "job_prospects": "Helpdesk Engineers play a crucial role in providing technical support to ensure the smooth functioning of IT systems within an organization.",
    },
    "Information Security Specialist": {
        "job_description": "Information Security Specialists implement and manage security measures to protect sensitive information and systems from unauthorized access, attacks, and breaches...",
        "prerequisites": "A degree in information security, cybersecurity, or a related field is typically required. Strong knowledge of cybersecurity principles and technologies is essential...",
        "job_stats": "Average CTC: $110,000 per year",
        "skill_enhancement": "To excel in this role, professionals can enhance their skills in network security, encryption, and security risk management...",
        "courses_reference": 'Cybrary - Certified Information Systems Security Professional (CISSP), edX - Computer and Information Security, Books - "Hacking: The Art of Exploitation"',
        "job_prospects": "Information Security Specialists are crucial for organizations aiming to protect sensitive data and maintain the integrity of their IT systems.",
    },
    "Networking Engineer": {
        "job_description": "Networking Engineers design, implement, and maintain computer networks for efficient data communication. They work on the configuration, optimization, and troubleshooting of network infrastructure...",
        "prerequisites": "A degree in computer science, information technology, or a related field is typically required. Strong knowledge of networking protocols and technologies is essential...",
        "job_stats": "Average CTC: $90,000 per year",
        "skill_enhancement": "To excel in this role, professionals can enhance their skills in network design, routing, and security...",
        "courses_reference": 'Cisco Networking Academy - CCNA: Introduction to Networks, LinkedIn Learning - CompTIA Network+ (N10-007) Cert Prep, Books - "Computer Networking: Principles, Protocols, and Practice"',
        "job_prospects": "Networking Engineers are essential for organizations to maintain reliable and secure communication infrastructures.",
    },
    "Project Manager": {
        "job_description": "Project Managers coordinate and oversee projects to ensure they are completed on time, within scope, and within budget. They work closely with team members and stakeholders to achieve project goals...",
        "prerequisites": "A degree in project management, business administration, or a related field is typically required. Strong leadership, communication, and organizational skills are essential...",
        "job_stats": "Average CTC: $110,000 per year",
        "skill_enhancement": "To excel in this role, professionals can enhance their skills in project planning, risk management, and leadership...",
        "courses_reference": 'Project Management Institute (PMI) - Project Management Professional (PMP) Certification, edX - Agile Project Management, Books - "The Art of Project Management"',
        "job_prospects": "Project Managers play a crucial role in ensuring the successful execution of projects, making them essential in various industries.",
    },
    "Software Developer": {
        "job_description": "Software Developers design, code, and test software applications for various platforms. They work on creating efficient and functional software solutions based on project requirements...",
        "prerequisites": "A degree in computer science, software engineering, or a related field is typically required. Strong programming skills in languages such as Python, Java, or C++ are essential...",
        "job_stats": "Average CTC: $100,000 per year",
        "skill_enhancement": "To excel in this role, professionals can enhance their skills in software development, version control, and problem-solving...",
        "courses_reference": 'Udacity - Full Stack Web Developer Nanodegree, Coursera - Software Engineering Specialization, Books - "Clean Code: A Handbook of Agile Software Craftsmanship"',
        "job_prospects": "Software Developers are in high demand across industries, contributing to the creation of innovative software solutions.",
    },
    "Software Tester": {
        "job_description": "Software Testers evaluate software applications to ensure they meet quality standards and requirements. They design and execute test cases, identify bugs, and collaborate with developers to ensure software quality...",
        "prerequisites": "A degree in computer science, software engineering, or a related field may be preferred. Strong attention to detail and analytical skills are essential...",
        "job_stats": "Average CTC: $80,000 per year",
        "skill_enhancement": "To excel in this role, professionals can enhance their skills in testing methodologies, automated testing, and bug tracking...",
        "courses_reference": 'Udemy - Complete Guide to Manual Software Testing, LinkedIn Learning - ISTQB Certified Tester Foundation Level, Books - "Foundations of Software Testing"',
        "job_prospects": "Software Testers play a crucial role in ensuring the functionality and reliability of software applications.",
    },
    "Technical Writer": {
        "job_description": "Technical Writers create clear and concise documentation for technical products and processes. They work on producing user manuals, guides, and other documentation to help users understand and use technical products...",
        "prerequisites": "A degree in technical writing, communication, or a related field is typically required. Strong writing and communication skills are essential...",
        "job_stats": "Average CTC: $70,000 per year",
        "skill_enhancement": "To excel in this role, professionals can enhance their skills in technical writing, document design, and collaboration...",
        "courses_reference": 'Udemy - Technical Writing and Editing, Coursera - Technical Writing Masterclass, Books - "The Elements of Style"',
        "job_prospects": "Technical Writers contribute to the effective communication of technical information, making their role essential in industries such as IT, manufacturing, and healthcare.",
    },
    "Unknown Career": {
        "job_description": "Information not available.",
        "prerequisites": "Information not available.",
        "job_stats": "Information not available.",
        "skill_enhancement": "Information not available.",
        "courses_reference": "Information not available.",
        "job_prospects": "Job prospects for the predicted career are not available at the moment.",
    },
}

skills_names = [
    "Database Fundamentals",
    "Computer Architecture",
    "Distributed Computing Systems",
    "Cyber Security",
    "Networking",
    "Development",
    "Programming Skills",
    "Project Management",
    "Computer Forensics Fundamentals",
    "Technical Communication",
    "AI ML",
    "Software Engineering",
    "Business Analysis",
    "Communication skills",
    "Data Science",
    "Troubleshooting skills",
    "Graphics Designing",
]

jobs_dict = {
    0: "AI ML Specialist",
    1: "API Integration Specialist",
    2: "Application Support Engineer",
    3: "Business Analyst",
    4: "Customer Service Executive",
    5: "Cyber Security Specialist",
    6: "Data Scientist",
    7: "Database Administrator",
    8: "Graphics Designer",
    9: "Hardware Engineer",
    10: "Helpdesk Engineer",
    11: "Information Security Specialist",
    12: "Networking Engineer",
    13: "Project Manager",
    14: "Software Developer",
    15: "Software Tester",
    16: "Technical Writer",
}
